# Generated by Django 5.0.7 on 2024-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancha',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancha',
            name='ubicacion_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancha',
            name='ubicacion_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcancha',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcancha',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcancha',
            name='ubicacion_x',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcancha',
            name='ubicacion_y',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=10),
            preserve_default=False,
        ),
    ]
