# Generated by Django 5.0.7 on 2024-11-15 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadio', '0003_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
